### ISSUE TITLE
Doesn't work with Sphinx 1.8

### ISSUE THREAD

**Issue by sloria** [humitos/sphinx-version-warning#17]
I get the following error when building with Sphinx>=1.8:

```
Running Sphinx v1.8.1
loading translations [en]... done
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/marshmallow/envs/2.x-line-versionwarning/lib/python3.5/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/marshmallow/envs/2.x-line-versionwarning/lib/python3.5/site-packages/sphinx/application.py", line 251, in __init__
    self.emit('config-inited', self.config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/marshmallow/envs/2.x-line-versionwarning/lib/python3.5/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/marshmallow/envs/2.x-line-versionwarning/lib/python3.5/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
TypeError: generate_versionwarning_data_json() takes 1 positional argument but 2 were given

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/marshmallow/envs/2.x-line-versionwarning/lib/python3.5/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
TypeError: generate_versionwarning_data_json() takes 1 positional argument but 2 were given
```

This happens on locally and on ReadTheDocs.

**Comment by sloria** [comment]
Great! Thanks for the fix. I'll try it later today.
