### ISSUE TITLE
`config.versionwarning_message_placeholder` syntax error on translated documentations

### ISSUE THREAD

**Issue by MrGeneration** [humitos/sphinx-version-warning#35]
### Basic input
* Used platform: readthedocs
* Sphinx: v1.8.5

### Intro 
We've just started with custom version warnings, thanks for the project! 
After testing and roll out on our main documentation (EN) I prepared the version for the german translation (DE). 
The build process failed with:

```
Running Sphinx v1.8.5
loading translations [de]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/versionwarning/extension.py", line 5, in <module>
    from .signals import generate_versionwarning_data_json
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/versionwarning/signals.py", line 41
    **{config.versionwarning_message_placeholder: '<a href="#"></a>'},
                                                                     ^
SyntaxError: invalid syntax

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/versionwarning/extension.py", line 5, in <module>
    from .signals import generate_versionwarning_data_json
  File "/home/docs/checkouts/readthedocs.org/user_builds/zammad-admin-documentation-german/envs/version3.6/lib/python2.7/site-packages/versionwarning/signals.py", line 41
    **{config.versionwarning_message_placeholder: '<a href="#"></a>'},
                                                                     ^
SyntaxError: invalid syntax
```

The branch that was used was the same like the english version. 
This is the affected branch: https://github.com/zammad/zammad-admin-documentation/tree/version3.6
The relevant `conf.py` parts for the extensions are these:

https://github.com/zammad/zammad-admin-documentation/blob/version3.6/conf.py#L55-L85

Local compiling in both languages works as expected. 
The data-json is also generated as I do expect it:

```
{
    "meta": {
        "api_url": "https://readthedocs.org/api/v2/"
    },
    "banner": {
        "html": "\n    <div id=\"version-warning-banner\" class=\"admonition warning\">\n        <p class=\"first admonition-title\">Warning</p>\n            <p class=\"last\">\n                You're viewing a <strong>pre-release</strong> version of this documentation! If you want to see the stable, current version of this documentation, please see <a href=\"https://admin-docs.zammad.org/en/latest/\" title=\"current documentation version\">here</a>.\n            </p>\n    </div>",
        "id_div": "version-warning-banner",
        "body_selector": "div.document",
        "custom": true
    },
    "project": {
        "slug": "zammad-admin-documentation"
    },
    "version": {
        "slug": "pre-release"
    }
}
```

Am I missing something or does the readthedoc environment do something so specific different which breaks `signal.py`?
If something is missing, please bear with me, I'll provide further feedback if I can.

**Comment by humitos** [comment]
I think this is a problem with Python2 that does not support that trailing comma. Can you use Python3 instead?

**Comment by MrGeneration** [comment]
Oh geez, didn't notice that the translation version in readthedocs was still on python 2.
My bad, thanks - it's now coming past the part that was failing. 🙈
